<?php

namespace BitCode\FI\Core\Util;

final class AllTriggersName
{
    public static function allTriggersName()
    {
        return [
            'AcademyLms'        => ['name' => 'Academy Lms',  'isPro' => true, 'is_active' => false],
            'ActionHook'        => ['name' => 'Action Hook',  'isPro' => true, 'is_active' => false],
            'Affiliate'         => ['name' => 'Affiliate',  'isPro' => true, 'is_active' => false],
            'Amelia'            => ['name' => 'Amelia',  'isPro' => true, 'is_active' => false],
            'ARForm'            => ['name' => 'ARForm',  'isPro' => true, 'is_active' => false],
            'ARMember'          => ['name' => 'ARMember',  'isPro' => true, 'is_active' => false],
            'Beaver'            => ['name' => 'Beaver',  'isPro' => true, 'is_active' => false],
            'BitAssist'         => ['name' => 'Bit  Assist',  'isPro' => true, 'is_active' => false],
            'Breakdance'        => ['name' => 'Breakdance',  'isPro' => true, 'is_active' => false],
            'Bricks'            => ['name' => 'Bricks',  'isPro' => true, 'is_active' => false],
            'Bricksforge'       => ['name' => 'Bricksforge',  'isPro' => true, 'is_active' => false],
            'Brizy'             => ['name' => 'Brizy',  'isPro' => true, 'is_active' => false],
            'BuddyBoss'         => ['name' => 'BuddyBoss',  'isPro' => true, 'is_active' => false],
            'CartFlow'          => ['name' => 'CartFlow',  'isPro' => true, 'is_active' => false],
            'Coblocks'          => ['name' => 'CoBlocks Form',  'isPro' => true, 'is_active' => false],
            'Divi'              => ['name' => 'Divi',  'isPro' => true, 'is_active' => false],
            'Dokan'             => ['name' => 'Dokan',  'isPro' => true, 'is_active' => false],
            'EDD'               => ['name' => 'Easy Digital Downloads',  'isPro' => true, 'is_active' => false],
            'EssentialBlocks'   => ['name' => 'Essential Blocks',  'isPro' => true, 'is_active' => false],
            'EVF'               => ['name' => 'Everest Forms',  'isPro' => true, 'is_active' => false],
            'FF'                => ['name' => 'Fluent Forms',  'isPro' => true, 'is_active' => false],
            'FluentBooking'     => ['name' => 'Fluent Booking',  'isPro' => true, 'is_active' => false],
            'FluentCrm'         => ['name' => 'Fluent CRM',  'isPro' => true, 'is_active' => false],
            'FluentSupport'     => ['name' => 'Fluent Support',  'isPro' => true, 'is_active' => false],
            'FormCraft'         => ['name' => 'FormCraft3',  'isPro' => true, 'is_active' => false],
            'Formidable'        => ['name' => 'Formidable',  'isPro' => true, 'is_active' => false],
            'Forminator'        => ['name' => 'Forminator',  'isPro' => true, 'is_active' => false],
            'GamiPress'         => ['name' => 'GamiPress',  'isPro' => true, 'is_active' => false],
            'GF'                => ['name' => 'Gravity Forms',  'isPro' => true, 'is_active' => false],
            'GiveWp'            => ['name' => 'GiveWp',  'isPro' => true, 'is_active' => false],
            'Groundhogg'        => ['name' => 'Groundhogg',  'isPro' => true, 'is_active' => false],
            'gutenaForms'       => ['name' => 'Gutena Forms',  'isPro' => true, 'is_active' => false],
            'Happy'             => ['name' => 'Happy Forms',  'isPro' => true, 'is_active' => false],
            'Hustle'            => ['name' => 'Hustle',  'isPro' => true, 'is_active' => false],
            'JetEngine'         => ['name' => 'JetEngine',  'isPro' => true, 'is_active' => false],
            'JetForm'           => ['name' => 'JetForm Builder',  'isPro' => true, 'is_active' => false],
            'Kadence'           => ['name' => 'Kadence Blocks Form',  'isPro' => true, 'is_active' => false],
            'KaliForms'         => ['name' => 'Kali Forms',  'isPro' => true, 'is_active' => false],
            'LearnDash'         => ['name' => 'LearnDash LMS',  'isPro' => true, 'is_active' => false],
            'LifterLms'         => ['name' => 'LifterLMS',  'isPro' => true, 'is_active' => false],
            'MailPoet'          => ['name' => 'MailPoet',  'isPro' => true, 'is_active' => false],
            'Mailster'          => ['name' => 'Mailster',  'isPro' => true, 'is_active' => false],
            'MasterStudyLms'    => ['name' => 'MasterStudyLms',  'isPro' => true, 'is_active' => false],
            'Memberpress'       => ['name' => 'Memberpress',  'isPro' => true, 'is_active' => false],
            'Met'               => ['name' => 'Met Form',  'isPro' => true, 'is_active' => false],
            'MetaBox'           => ['name' => 'MB Frontend Submission',  'isPro' => true, 'is_active' => false],
            'NF'                => ['name' => 'Ninja Forms',  'isPro' => true, 'is_active' => false],
            'OptinMonster'      => ['name' => 'OptinMonster',  'isPro' => true, 'is_active' => false],
            'PaidMembershipPro' => ['name' => 'Paid Membership Pro',  'isPro' => true, 'is_active' => false],
            'PiotnetAddon'      => ['name' => 'PiotnetAddon',  'isPro' => true, 'is_active' => false],
            'PiotnetAddonForm'  => ['name' => 'PiotnetAddonForm',  'isPro' => true, 'is_active' => false],
            'PiotnetForms'      => ['name' => 'Piotnet Forms',  'isPro' => true, 'is_active' => false],
            'PopupMaker'        => ['name' => 'Popup Maker',  'isPro' => true, 'is_active' => false],
            'Post'              => ['name' => 'WP Post',  'isPro' => true, 'is_active' => false],
            'Rafflepress'       => ['name' => 'Rafflepress',  'isPro' => true, 'is_active' => false],
            'Rafflepress'       => ['name' => 'Rafflepress',  'isPro' => true, 'is_active' => false],
            'Registration'      => ['name' => 'WP User Registration',  'isPro' => true, 'is_active' => false],
            'RestrictContent'   => ['name' => 'Restrict Content',  'isPro' => true, 'is_active' => false],
            'SiteOriginWidgets' => ['name' => 'SiteOrigin Widgets',  'isPro' => true, 'is_active' => false],
            'SliceWp'           => ['name' => 'SliceWp',  'isPro' => true, 'is_active' => false],
            'SolidAffiliate'    => ['name' => 'Solid Affiliate',  'isPro' => true, 'is_active' => false],
            'Spectra'           => ['name' => 'Spectra',  'isPro' => true, 'is_active' => false],
            'StudioCart'        => ['name' => 'StudioCart',  'isPro' => true, 'is_active' => false],
            'SureCart'          => ['name' => 'SureCart',  'isPro' => true, 'is_active' => false],
            'SureForms'         => ['name' => 'SureForms',  'isPro' => true, 'is_active' => false],
            'SureMembers'       => ['name' => 'SureMembers',  'isPro' => true, 'is_active' => false],
            'ThriveApprentice'  => ['name' => 'ThriveApprentice',  'isPro' => true, 'is_active' => false],
            'Tripetto'          => ['name' => 'Tripetto',  'isPro' => true, 'is_active' => false],
            'TutorLms'          => ['name' => 'Tutor LMS',  'isPro' => true, 'is_active' => false],
            'UltimateMember'    => ['name' => 'UltimateMember',  'isPro' => true, 'is_active' => false],
            'Webhook'           => ['name' => 'Webhook',  'isPro' => true, 'is_active' => false],
            'WeForms'           => ['name' => 'WeForms',  'isPro' => true, 'is_active' => false],
            'WPCourseware'      => ['name' => 'WP Courseware',  'isPro' => true, 'is_active' => false],
            'WPEF'              => ['name' => 'eForm',  'isPro' => true, 'is_active' => false],
            'WPForo'            => ['name' => 'wpForo Forum',  'isPro' => true, 'is_active' => false],
            'WPFunnels'         => ['name' => 'WPFunnels',  'isPro' => true, 'is_active' => false],
            'WPJobManager'      => ['name' => 'WP Job Manager',  'isPro' => true, 'is_active' => false],
            'WSForm'            => ['name' => 'WSForm',  'isPro' => true, 'is_active' => false],
        ];
    }
}
